### ISSUE TITLE
Custom tag name

### ISSUE THREAD

**Issue by estshy** [rwjblue/ember-template-lint#112]
This package breaks when there is a a custom html tag with a dash inside and it should not as Ember angle bracket components will be introduced soon.

```
<foo-bar>
</foo-bar>
```

> Cannot read property 'tag' of undefined

**Comment by rwjblue** [comment]
Thanks for reporting!  Can you share the full stack trace?

**Comment by estshy** [comment]
```
undefined: Cannot read property 'tag' of undefined ((..)/template): 
`TypeError: Cannot read property 'tag' of undefined
  at BasePlugin.LogStaticStrings._getBareStringAttribute (/ember-app/node_modules/ember-template-lint/lib/rules/lint-bare-strings.js:134:39)
  at BasePlugin.TextNode (/ember-app/node_modules/ember-template-lint/lib/rules/lint-bare-strings.js:111:16)
  at invokeVisitorEnter (/ember-app/node_modules/ember-template-lint/lib/rules/base.js:14:15)
  at visitor.enter (/ember-app/node_modules/ember-template-lint/lib/rules/base.js:83:11)
  at visitNode (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:18:28)
  at visitKey (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:55:19)
  at visitNode (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:25:7)
  at visitArray (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:71:18)
  at visitKey (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:53:5)
  at visitNode (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:25:7)
  at visitArray (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:71:18)
  at visitKey (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:53:5)
  at visitNode (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:25:7)
  at Object.traverse (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:110:3)
  at BasePlugin.transform (/ember-app/node_modules/ember-template-lint/lib/rules/base.js:41:17)
  at Object.preprocess (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/parser.js:45:25)
  at compileSpec (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-compiler/compiler.js:39:35)
  at compile (/ember-app/node_modules/htmlbars/dist/cjs/htmlbars-compiler/compiler.js:88:46)
  at Linter.verify (/ember-app/node_modules/ember-template-lint/lib/index.js:86:7)
  at TemplateLinter.processString (/ember-app/node_modules/ember-cli-template-lint/broccoli-template-linter.js:91:28)
  at Promise.then.result.output (/ember-app/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
  at lib$rsvp$$internal$$initializePromise (/ember-app/node_modules/rsvp/dist/rsvp.js:541:9)
  at new lib$rsvp$promise$$Promise (/ember-app/node_modules/rsvp/dist/rsvp.js:757:9)
  at /ember-app/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:40:18
  at lib$rsvp$$internal$$tryCatch (/ember-app/node_modules/rsvp/dist/rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/ember-app/node_modules/rsvp/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/ember-app/node_modules/rsvp/dist/rsvp.js:476:11)
  at lib$rsvp$asap$$flush (/ember-app/node_modules/rsvp/dist/rsvp.js:1198:9)
  at doNTCallback0 (node.js:417:9)
  at process._tickCallback (node.js:346:13)
```

**Comment by estshy** [comment]
@rwjblue Could you update the version on NPM as well? Current release seems to be 6.x where npm uses up to 5.x.

**Comment by estshy** [comment]
@rwjblue The problem persists in v0.6.1

@rwjblue The problem persists in v0.6.1

```
<md-autocomplete-wrap id= {{autocompleteWrapperId}} role="listbox" layout="row" class="{{if notFloating "md-whiteframe-z1"}} {{if notHidden "md-menu-showing"}}"></md-autocomplete-wrap>
```

```
undefined: Cannot read property 'tag' of undefined (input-language-autocomplete/template): 
`TypeError: Cannot read property 'tag' of undefined
  at BasePlugin.LogStaticStrings._getBareStringAttribute (ember-app/node_modules/ember-template-lint/lib/rules/lint-bare-strings.js:134:39)
  at BasePlugin.TextNode (ember-app/node_modules/ember-template-lint/lib/rules/lint-bare-strings.js:111:16)
  at invokeVisitorEnter (ember-app/node_modules/ember-template-lint/lib/rules/base.js:14:15)
  at visitor.enter (ember-app/node_modules/ember-template-lint/lib/rules/base.js:83:11)
  at visitNode (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:18:28)
  at visitKey (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:55:19)
  at visitNode (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:25:7)
  at visitArray (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:71:18)
  at visitKey (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:53:5)
  at visitNode (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:25:7)
  at visitArray (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:71:18)
  at visitKey (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:53:5)
  at visitNode (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:25:7)
  at Object.traverse (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/traversal/traverse.js:110:3)
  at BasePlugin.transform (ember-app/node_modules/ember-template-lint/lib/rules/base.js:41:17)
  at Object.preprocess (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-syntax/parser.js:45:25)
  at compileSpec (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-compiler/compiler.js:39:35)
  at compile (ember-app/node_modules/htmlbars/dist/cjs/htmlbars-compiler/compiler.js:88:46)
  at Linter.verify (ember-app/node_modules/ember-template-lint/lib/index.js:86:7)
  at TemplateLinter.processString (ember-app/node_modules/ember-cli-template-lint/broccoli-template-linter.js:91:28)
  at Promise.then.result.output (ember-app/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
  at initializePromise (ember-app/node_modules/rsvp/dist/rsvp.js:588:5)
  at new Promise (ember-app/node_modules/rsvp/dist/rsvp.js:1076:31)
  at ember-app/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:40:18
  at tryCatch (ember-app/node_modules/rsvp/dist/rsvp.js:538:12)
  at invokeCallback (ember-app/node_modules/rsvp/dist/rsvp.js:553:13)
  at publish (ember-app/node_modules/rsvp/dist/rsvp.js:521:7)
  at flush (ember-app/node_modules/rsvp/dist/rsvp.js:2373:5)
  at doNTCallback0 (node.js:417:9)
  at process._tickCallback (node.js:346:13)
```
